Traceback (most recent call last):
  File "/mnt/beegfs/homes/simondn/RashomonActiveLearning/Code/RunSimulation.py", line 56, in <module>
    SimulationResults = OneIterationFunction(SimulationConfigInput)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/beegfs/homes/simondn/RashomonActiveLearning/Code/utils/Main/OneIterationFunction.py", line 78, in OneIterationFunction
    LearningProcedureOutput = LearningProcedure(SimulationConfigInputUpdated = SimulationConfigInput)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/beegfs/homes/simondn/RashomonActiveLearning/Code/utils/Main/LearningProcedure.py", line 49, in LearningProcedure
    TestErrorOutput = TestErrorFunction(InputModel = Model, df_Test = SimulationConfigInputUpdated["df_Test"], Type = SimulationConfigInputUpdated["Type"])
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/beegfs/homes/simondn/RashomonActiveLearning/Code/utils/Prediction/TestErrorFunction.py", line 60, in TestErrorFunction
    Prediction = InputModel.predict(df_Test.loc[:, df_Test.columns != "Y"])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/homes/simondn/.local/lib/python3.11/site-packages/sklearn/ensemble/_forest.py", line 904, in predict
    proba = self.predict_proba(X)
            ^^^^^^^^^^^^^^^^^^^^^
  File "/homes/simondn/.local/lib/python3.11/site-packages/sklearn/ensemble/_forest.py", line 946, in predict_proba
    X = self._validate_X_predict(X)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/homes/simondn/.local/lib/python3.11/site-packages/sklearn/ensemble/_forest.py", line 641, in _validate_X_predict
    X = self._validate_data(
        ^^^^^^^^^^^^^^^^^^^^
  File "/homes/simondn/.local/lib/python3.11/site-packages/sklearn/base.py", line 608, in _validate_data
    self._check_feature_names(X, reset=reset)
  File "/homes/simondn/.local/lib/python3.11/site-packages/sklearn/base.py", line 535, in _check_feature_names
    raise ValueError(message)
ValueError: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- ClusterLabels
- d_nX

